apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
spec:
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.properties.port }}
      targetPort: 8761
  type: ClusterIP
  