name: Deploy Eureka Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run test
        run: ./gradlew test --no-daemon

  build-jar:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build JAR
        run: ./gradlew bootJar --no-daemon

      - name: Upload JAR atrifact
        uses: actions/upload-artifact@v4
        with:
          name: eureka-app
          path: build/libs/*.jar

  login-to-registry:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URI }}/shop-registry/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: login-to-registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: Azure/setup-kubectl@v4

      - name: Setup Helm
        uses: Azure/setup-helm@v3

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Helm upgrade
        run: |
          helm upgrade --install my-release ./eureka-server --namespace eureka-server --set properties.image.name=${{ github.repository }} --set properties.image.tag=${{ github.sha }}
